- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  # pre_tasks:
  # - name: Update Apt
  #   become: true
  #   apt:
      # force_apt_get: true
      # update_cache: true
      # state: present
    # tags:
    # - node
    # - zsh
    # - nvim
    # - ssh
  tasks:
  # - include: tasks/core-setup.yml
  # - include: tasks/ssh.yml
  - include_tasks: tasks/zsh.yml
  - include_tasks: tasks/dotfile.yml
  # - include: tasks/nvim.yml
  # - include: tasks/node.yml
  # - include: tasks/slack-setup.yml
  # - include: tasks/core-setup.yml


