- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  # pre_tasks:
  # - name: Update Apt
  #   become: true
  #   apt:
      # force_apt_get: true
      # update_cache: true
      # state: present
    # tags:
    # - node
    # - zsh
    # - nvim
    # - ssh
  tasks:
  - include_tasks: tasks/ssh.yml
    tags:
      - always
  - include_tasks: tasks/core-setup.yml
    tags:
      - always
  - include_tasks: tasks/zsh.yml
    tags:
      - always
  - include_tasks: tasks/tmux.yml
    tags:
      - always
  - include_tasks: tasks/dotfile.yml
    tags:
      - always
  - include_tasks: tasks/nvim.yml
    tags:
      - always
  - include_tasks: tasks/node.yml
    tags:
      - always
