- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: false
      update_cache: false
      state: present
    tags:
    - node
    - zsh
    - nvim
    - ssh
  tasks:
  # - include: tasks/ssh.yml
  - include: tasks/git.yml
  # - name: Cloning .dotfiles
  #   ansible.builtin.git:
  #     repo: 'git@github.com:pietow/store-accecc-token.git'
  #     dest: "{{ lookup('env', 'HOME') }}/myrepo"
  #     accept_hostkey: yes
  #     force: yes
  #     ssh_opts: "-o StrictHostKeyChecking=no"
  # - include: tasks/zsh.yml
  # - include: tasks/nvim.yml
  # - include: tasks/node.yml


