- hosts: localhost
  vars_prompt:
    - name: passphrase
      prompt: "Enter your password ?"
  tasks:
  # - name: Print a message
  #   ansible.builtin.debug:
  #     msg: 'Logging in as {{ passphrase }}'
  # - name: Run ssh-agent
  #   shell: exec ssh-agent $SHELL
  #   tags:
  #     - git
  # - name: Install expect
  #   apt: name=expect
  #   tags:
  #     - git
  - name:  add Key to ssh agent
    ansible.builtin.shell: |
      spawn ssh-add 

      expect "*?assphrase:*"
      send "{{ passphrase }}\n" 

      exit 0
    register: shell_result
    args:
      executable: /usr/bin/expect
    delegate_to: localhost
    tags:
      - git
  - debug:
      var: shell_result.stdout_lines
  - debug:
      var: shell_result
