- name: Install tmux
  apt: name=tmux
  become: yes
  tags:
    - tmux
- name: Install tmux-resurrect
  shell: sh -c "git clone https://github.com/tmux-plugins/tmux-resurrect ~/clone/path" 
  ignore_errors: yes
  tags:
    - tmux