- name: Prints two lines of messages, but only if there is an environment value set
  ansible.builtin.debug:
    msg:
    - "check for right $HOME and $USER: {{ lookup('ansible.builtin.env', 'HOME') }} {{ lookup('ansible.builtin.env', 'USER') }}"
  tags: zsh
- name: Install zsh
  apt: name=zsh
  become: yes
  tags:
    - zsh
- name: Change shell
  shell: chsh -s 'which zsh'  
  become: yes
  tags:
    - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-syntax-highlighting
  shell: sh -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - zsh
- name: Install zsh-autosuggestions
  shell: sh -c "git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions" 
  tags:
    - zsh
- name: remove zshrc
  shell: rm ~/.zshrc
  tags:
    - zsh
