- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change shell
  shell: chsh -s 'which zsh'
  tags:
    - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-syntax-highlighting
  shell: sh -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - zsh
- name: Install zsh-autosuggestions
  shell: sh -c "git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions" 
  tags:
    - zsh
